export interface BlogPost {
  slug: string;
  title: string;
  excerpt: string;
  /** Display date, e.g. "21 September 2026" */
  date: string;
  category: string;
  readTime: string;
  published: boolean;
}

/**
 * Single source of truth for the blog index.
 *
 * Both the blog listing page and the sitemap read this array, so a new post
 * is registered in ONE place. Newest first.
 */
export const posts: BlogPost[] = [
  {
    slug: "why-does-my-drain-smell",
    title: "Why Does My Drain Smell? The Five Usual Causes",
    excerpt: "A smelly drain is telling you something. Here are the five things that actually cause it, how to tell which one you have, and the 30-second fix that solves a good share of them.",
    date: "21 September 2026",
    category: "Blocked Drains",
    readTime: "5 min read",
    published: true,
  },
  {
    slug: "backflow-prevention-testing-explained",
    title: "Backflow Prevention: Does Your Property Need Annual Testing?",
    excerpt: "Backflow devices stop contaminated water being drawn back into the drinking supply, and testable ones need checking yearly. Here's who needs one and what a test involves.",
    date: "21 September 2026",
    category: "Backflow Prevention",
    readTime: "6 min read",
    published: true,
  },
  {
    slug: "pipe-relining-vs-pipe-replacement",
    title: "Pipe Relining vs Pipe Replacement: Which Does Your Home Need?",
    excerpt: "Relining rebuilds a damaged pipe from the inside with no digging. Replacement means excavation. Here's how to tell which one your drain actually needs — and what to ask before you commit.",
    date: "25 August 2026",
    category: "Pipe Relining",
    readTime: "5 min read",
    published: true,
  },
  {
    slug: "gutters-downpipes-storm-season-checklist",
    title: "Gutters and Downpipes: The Storm Season Checklist for Sydney Homes",
    excerpt: "Most storm damage inside a home starts with a blocked gutter, not a hole in the roof. Here's how to check your gutters, downpipes, and flashings before the first big downpour.",
    date: "25 August 2026",
    category: "Roof Plumbing",
    readTime: "5 min read",
    published: true,
  },
  {
    slug: "why-your-toilet-keeps-running",
    title: "Why Your Toilet Keeps Running (and How to Fix It)",
    excerpt: "That constant hiss in the bathroom is wasting thousands of litres a month. Here are the three usual culprits inside the cistern — and how to fix them before your water bill spikes.",
    date: "16 July 2026",
    category: "Taps & Toilets",
    readTime: "5 min read",
    published: true,
  },
  {
    slug: "how-to-detect-a-hidden-water-leak",
    title: "How to Detect a Hidden Water Leak Before It Costs You Thousands",
    excerpt: "A hidden leak can rot timber and ruin ceilings before you ever see a drop. Here's how to catch one early using the water meter test and six warning signs.",
    date: "16 July 2026",
    category: "Leak Detection",
    readTime: "6 min read",
    published: true,
  },
  {
    slug: "blocked-stormwater-drains",
    title: "Blocked Stormwater Drains: Why Your Yard Floods When It Rains",
    excerpt: "If your yard turns into a lake every time it rains hard, your stormwater drains are blocked. Here's what causes it, the warning signs, and how to fix it before water reaches your home.",
    date: "16 July 2026",
    category: "Stormwater",
    readTime: "6 min read",
    published: true,
  },
  {
    slug: "winter-plumbing-checklist-sydney",
    title: "Winter Plumbing Checklist: How to Prepare Your Sydney Home for Cold Weather",
    excerpt: "Sydney winters are mild, but they still cause burst pipes, hot water failures, and blocked drains. Here's a simple checklist to prepare your home before the cold hits.",
    date: "3 June 2026",
    category: "Seasonal",
    readTime: "6 min read",
    published: true,
  },
  {
    slug: "why-hot-water-struggles-in-winter",
    title: "Why Your Hot Water Struggles in Winter (and How to Fix It)",
    excerpt: "Lukewarm showers, water that runs out fast, or no hot water at all? Here's why hot water systems struggle every Sydney winter — and what to do before yours fails.",
    date: "3 June 2026",
    category: "Hot Water",
    readTime: "6 min read",
    published: true,
  },
  {
    slug: "why-is-my-drain-blocked",
    title: "Why Is My Drain Blocked? The Most Common Causes in Australian Homes",
    excerpt: "A blocked drain is almost always caused by one of five things. Learn what's causing yours — and when to call a plumber.",
    date: "7 April 2026",
    category: "Blocked Drains",
    readTime: "6 min read",
    published: true,
  },
  {
    slug: "gas-leak-or-not",
    title: "Gas Leak or Not? How to Tell — and What to Do Immediately",
    excerpt: "If you smell gas indoors, treat it as a real leak until proven otherwise. Here's exactly what to do — and what not to do.",
    date: "10 April 2026",
    category: "Gas Safety",
    readTime: "5 min read",
    published: true,
  },
  {
    slug: "how-much-does-a-leaking-tap-cost",
    title: "How Much Does a Leaking Tap Actually Cost You? (The Numbers Might Surprise You)",
    excerpt: "A dripping tap might seem minor, but the water waste and hidden damage costs add up fast. Here's exactly what a leaking tap costs — and why you should fix it now.",
    date: "8 May 2026",
    category: "Taps & Toilets",
    readTime: "5 min read",
    published: true,
  },
  {
    slug: "what-to-do-in-a-plumbing-emergency",
    title: "What to Do in a Plumbing Emergency: A Step-by-Step Guide for Sydney Homeowners",
    excerpt: "Burst pipe? Flooding? Gas leak? Here's a clear, calm plan for the most common plumbing emergencies — so you know exactly what to do before a plumber arrives.",
    date: "8 May 2026",
    category: "Emergency Plumbing",
    readTime: "7 min read",
    published: true,
  },
  {
    slug: "how-to-choose-a-plumber-in-sydney",
    title: "How to Choose a Plumber in Sydney (Without Getting Ripped Off)",
    excerpt: "Choosing the wrong plumber can cost you hundreds. Here's exactly what to check before you hire — licence, insurance, pricing, and the red flags to avoid.",
    date: "8 May 2026",
    category: "Plumbing Advice",
    readTime: "6 min read",
    published: true,
  },
  {
    slug: "signs-your-hot-water-system-is-failing",
    title: "7 Signs Your Hot Water System Is About to Fail",
    excerpt: "Don't get caught with a cold shower. These 7 warning signs mean your hot water system is struggling — and what to do before it fails completely.",
    date: "8 May 2026",
    category: "Hot Water",
    readTime: "5 min read",
    published: true,
  },
  {
    slug: "how-to-prevent-blocked-drains",
    title: "How to Prevent Blocked Drains: A Room-by-Room Guide",
    excerpt: "Most blocked drains are 100% preventable. Here's exactly what to do in each room of your home to keep your drains clear and avoid expensive callouts.",
    date: "8 May 2026",
    category: "Blocked Drains",
    readTime: "5 min read",
    published: true,
  },
  {
    slug: "gas-vs-electric-vs-heat-pump-hot-water",
    title: "Gas vs Electric vs Heat Pump Hot Water: Which Is Best for Your Sydney Home?",
    excerpt: "Choosing a hot water system is a 10-year decision. Compare gas, electric, and heat pump systems for Sydney homes — running costs, install costs, and reliability.",
    date: "20 May 2026",
    category: "Hot Water",
    readTime: "6 min read",
    published: true,
  },
  {
    slug: "tree-roots-in-drains",
    title: "Tree Roots in Your Drains: Why It Keeps Happening (and How to Stop It)",
    excerpt: "If your drain keeps blocking every few months, tree roots are almost always the culprit. Here's how they get in, and the three real fixes — from temporary to permanent.",
    date: "20 May 2026",
    category: "Blocked Drains",
    readTime: "5 min read",
    published: true,
  },
  {
    slug: "water-pressure-too-high-or-too-low",
    title: "Water Pressure Too High or Too Low? How to Diagnose It Yourself",
    excerpt: "Bad water pressure isn't just annoying — it can damage appliances or signal a hidden leak. Here's how to test your own pressure in 5 minutes and know when it's serious.",
    date: "20 May 2026",
    category: "Plumbing Advice",
    readTime: "6 min read",
    published: true,
  },
  {
    slug: "burst-pipe-first-5-minutes",
    title: "Burst Pipe at Home: The First 5 Minutes Before the Plumber Arrives",
    excerpt: "A burst pipe can dump hundreds of litres into your home in minutes. Here is exactly what to do in the first 5 minutes to stop the damage, before the plumber arrives.",
    date: "20 May 2026",
    category: "Emergency Plumbing",
    readTime: "5 min read",
    published: true,
  },
  {
    slug: "how-to-read-your-sydney-water-bill",
    title: "How to Read Your Sydney Water Bill (and Spot a Hidden Leak)",
    excerpt: "Your Sydney Water bill tells a story most people miss. Here is how to read it properly and how to spot a hidden leak that could be quietly draining hundreds of litres a day.",
    date: "20 May 2026",
    category: "Plumbing Advice",
    readTime: "6 min read",
    published: true,
  },
  {
    slug: "bathroom-renovation-plumbing-checklist",
    title: "Bathroom Renovation Plumbing Checklist for Sydney Homes",
    excerpt: "Planning a bathroom renovation? Get the plumbing right and the project flows smoothly. Get it wrong and you will pay for it twice. Here is the checklist every Sydney homeowner needs.",
    date: "20 May 2026",
    category: "Bathroom Renovations",
    readTime: "7 min read",
    published: true,
  },
];
